name: Build rolling-release on major platforms

on:
  push:
    branches:
    - main
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
        include:
          - os: ubuntu-latest
            pkg: diabaig.x86_64.zip
          - os: macos-latest
            pkg: diabaig.macos.zip
          #- os: windows-latest
          #  pkg: diabaig.windows.zip
          
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: |
          make
          make pkg

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.pkg }}
            path: build/${{ matrix.pkg }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: diabaig.x86_64.zip
          path: build/diabaig.x86_64
      - uses: actions/download-artifact@v4
        with:
          name: diabaig.macos.zip
          path: build/diabaig.macos.zip
      #- uses: actions/download-artifact@v4
      #  with:
      #    name: diabaig.windows.zip
      #    path: build/diabaig.windows.zip

      - name: Create or update latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          body: Automated rolling build for Linux, macOS, [Windows]
          files: build/**   # attach all binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

