name: Compile on all major platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make all 

    - name: upload binary
      uses: actions/upload-artifact@v4
      with:
          name: diabaig.x86_64
          path: build/linux/diabaig

     

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make all 

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make all 
  
