name: Build rolling-release on major platforms

on:
  push:
    branches:
    - main
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        
          - os: ubuntu-latest
            arch: x86_64
            pkg: diabaig.x86_64.zip
            
          # - os: ubuntu-latest
          #   arch: aarch64
          #   pkg: diabaig.aarch64.zip
            
          - os: macos-latest
            arch: arm64
            pkg: diabaig.macos.zip

          #- os: macos-latest
          #  arch: x86_64
          #  pkg: diabaig.macos.intel.zip
            
          #- os: ubuntu-latest
          #  pkg: diabaig.windows.zip
          #  target: windows
          
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      #- name: Install Dependencies
      #  if: ${{ matrix.target == 'windows' }}
      #  run: |
      #      curl -L https://github.com/wmcbrine/PDCurses/archive/refs/heads/master.zip -o PDCurses.zip
      #      unzip PDCurses.zip
      #      cp PDCurses-master/*.h include/
      #      cp PDCurses-master/wincon/* lib/windows/


      - name: Build 
        run: |
          make 
          make pkg


      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.pkg }}
            path: build/${{ matrix.pkg }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download linux x86_64 build artifacts
        uses: actions/download-artifact@v4
        with:
          name: diabaig.x86_64.zip
          path: build/diabaig.x86_64.zip
      
      # - name: Download linux aarch64 build artifacts
      # uses: actions/download-artifact@v4
      # with:
      #   name: diabaig.aarch64.zip
      #   path: build/diabaig.aarch64.zip   

      - name: Download macos arm64 build artifacts
        uses: actions/download-artifact@v4
        with:
          name: diabaig.macos.zip
          path: build/diabaig.macos.zip

      #- name: Download macos x86_64 build artifacts
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: diabaig.macos.intel.zip
      #    path: build/diabaig.macos.intel.zip
          
      #- name: Download macos x86_64 build artifacts
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: diabaig.windows.zip
      #    path: build/diabaig.windows.zip
      - name: Delete existing latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest --yes || true
          git tag -d latest || true
          git push origin :refs/tags/latest || true

      - name: Create latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: diabaig-latest
          body: |
            ## Latest Rolling Build
            
            Automated build for commit `${{ github.sha }}`

            **Binaries included:**
            - `diabaig.x86_64.zip`      : dynamically linked linux x86_64 package 
            - `diabaig.macos.zip`       : dynamically linked macos package
            
          files: build/**   # attach all binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

