name: Compile on all major platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make all 

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make all 

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make all 
  
