name: Build rolling-release on major platforms

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update && sudo apt-get install -y build-essential make
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install make
          fi
        shell: bash
        
      - name: Build
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            make.exe
            make.exe pkg
          else
            make
            make pkg
          fi

      - name: Set binary path
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "DIABAIG_PATH=./build/diabaig.86_64.zip" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "DIABAIG_PATH=./build/diabaig.macos.zip" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "DIABAIG_PATH=./diabaig.windows.zip" >> $GITHUB_ENV
          fi


      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
            name: ${{ env.DIABAIG_PATH }}
            path: ${{ env.DIABAIG_PATH }}

